---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-workspace
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: argo-clusterset
spec:
  clusterSelector:
    labelSelector:
      matchLabels:
        ocm.io/platform: argo
    selectorType: LabelSelector
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: argo-clusterset
  namespace: argo-workspace
spec:
  clusterSet: argo-clusterset
