apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-hello-world
  namespace: argo
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: call-whalesay-template
            templateRef:
              name: workflow-template-whalesay-template
              template: whalesay-template
            arguments:
              parameters:
                - name: message
                  value: "hello world"
